# Keys and BOT Data
StartupType = '0'  # 0 For starting up as a Bot, 1 for starting up as a Normal User
Token = ''  # Discord App Token (If StartupType is 0)
dsc_email = ''  # Discord Email (If StartupType is 1)
dsc_password = ''  # Discord Password (If StartupType is 1)
ClientID = ''  # Discord App Client ID
OwnerID = ''  # Your UniqueID for special permissions
Notifications = 'No'  # Experimental Pushbullet Notification Toggle
Pushbullet = ''  # Pushbullet API Key
OpenWeatherMapKey = ''  # Open Weather Map API Key
MashapeKey = ''  # Mashape API Key
RiotAPIKey = ''  # Riot Games API Key
GoogleAPIKey = ''  # Google API Key
LastFMAPIKey = ''  # LastFM API Key
ITADKey = ''  # IsThereAnyDeal API Key
SteamAPI = ''  # Steam API Key
SonarrKey = ''  # Sonarr API Key
mal_un = ''  # MyAnimeList Username
mal_pw = ''  # MyAnimeList Password
Prefix = '>>'  # Bot Command Prefix
# Commands
cmd_help = 'help'
cmd_modules = 'modules'
cmd_overwatch = 'overwatch'
cmd_league = 'league'
cmd_echo = 'echo'
cmd_bns = 'bnsstats'
cmd_bns_att = 'bnsatt'
cmd_bns_def = 'bnsdef'
cmd_osu = 'osu'
cmd_dota2 = 'dota2'
cmd_ud = 'ud'
cmd_weather = 'weather'
cmd_hearthstone = 'hearthstone'
cmd_pokemon = 'pokemon'
cmd_joke = 'joke'
cmd_rip = 'rip'
cmd_lfm = 'lastfm'
cmd_nsfw_permit = 'nsfwpermit'
cmd_nhentai = 'nhentai'
cmd_ehentai = 'ehentai'
cmd_gelbooru = 'gelbooru'
cmd_rule34 = 'rule34'
cmd_e621 = 'e621'
cmd_hentaims = 'hentaims'
cmd_itad = 'itad'
cmd_imdb = 'imdb'
cmd_jisho = 'jisho'
cmd_wk = 'wanikani'
cmd_wk_store = 'wksave'
cmd_anime = 'anime'
cmd_manga = 'manga'
cmd_vindi = 'es'
cmd_sonarr = 'sonarr'
cmd_handup = 'handup'
cmd_handdown = 'handdown'
cmd_takemic = 'takemic'
cmd_dropmic = 'dropmic'
cmd_repertoire = 'singers'
