CREATE TABLE IF NOT EXISTS NSFW (
	CHANNEL_ID	INTEGER PRIMARY KEY NOT NULL,
	PERMITTED	TEXT
);

CREATE TABLE IF NOT EXISTS KARAOKE (
	SINGER_ID	INTEGER PRIMARY KEY NOT NULL
);

CREATE TABLE IF NOT EXISTS POINT_SYSTEM (
	USER_ID		INTEGER PRIMARY KEY NOT NULL,
	POINTS		INTEGER,
	LVL		    INTEGER,
	LV_CHECK	INTEGER
);

CREATE TABLE IF NOT EXISTS WANIKANI (
	USER_ID		INTEGER PRIMARY KEY NOT NULL,
	WK_KEY		TEXT,
	WK_USERNAME	TEXT
);

CREATE TABLE IF NOT EXISTS KARAOKE_LIST (
	USER_ID		INTEGER PRIMARY KEY NOT NULL,
	USER_NAME	TEXT
);

CREATE TABLE IF NOT EXISTS GITHUB_LINKS (
    ID          INTEGER PRIMARY KEY NOT NULL,
    ADDED_BY    INTEGER NOT NULL,
    ADDED_DATE  INTEGER NOT NULL
    GH_USER     TEXT NOT NULL,
    GH_REPO     TEXT NOT NULL
);
