CREATE TABLE IF NOT EXISTS EVENT (
	id	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	userid	INTEGER,
	teamid	INTEGER
);

CREATE TABLE IF NOT EXISTS KARAOKE (
	server_id	INTEGER,
	ongoing		INTEGER,
	strict		INTEGER,
	channel		TEXT
);

CREATE TABLE IF NOT EXISTS KARAOKE_QUEUE (
	singer_id	INTEGER,
	server_id	INTEGER,
	queue		INTEGER
);

CREATE TABLE IF NOT EXISTS NSFW (
	CHANNEL_ID	INTEGER PRIMARY KEY NOT NULL,
	PERMITTED	TEXT
);

CREATE TABLE IF NOT EXISTS Vindictus_Scrolls (
	id              INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	name		TEXT,
	type		TEXT,
	rank		TEXT,
	enchantable_on	TEXT,
	effects		TEXT
);

CREATE TABLE IF NOT EXISTS WANIKANI (
	USER_ID		INTEGER PRIMARY KEY NOT NULL,
	WK_KEY		TEXT,
	WK_USERNAME	INTEGER
);

/*
missing tables:
POINT_SYSTEM
*/
